apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-config
data:
  docker-conf: |
    {
    	"auths": {
    		"your.registry.goes.here.com": {
    			"auth": "...",
    			"email": "..."
    		}
    	}
    }

---
apiVersion: v1
kind: Service
metadata:
  name: clairsvc
  labels:
    app: clair
spec:
  ports:
  - port: 6060
    protocol: TCP
    name: clair-port0
  - port: 6061
    protocol: TCP
    name: clair-port1
  selector:
    clair: clair
---
apiVersion: v1
kind: Service
metadata:
  name: kate
spec:
  clusterIP: None
  ports:
  - port: 8080
    name: http
    targetPort: http
    protocol: TCP
  selector:
    kate: kate
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: clair-and-kate
spec:
  replicas: 1
  template:
    metadata:
      labels:
        clair: clair
        kate: kate
    spec:
      volumes:
        - name: docker-config
          configMap:
            name: docker-config
            items:
            - key: docker-conf
              path: config.json
        - name: docker-socket
          hostPath:
            path: /var/run/docker.socket
        - name: docker
          hostPath:
            path: /var/lib/docker
        - name: varrun
          hostPath:
            path: /var/run
        - name: sysfs
          hostPath:
            path: /sys
        - name: secret-volume
          secret:
            secretName: clairsecret
        - name: cve
          persistentVolumeClaim:
            claimName: clair-cve-claim
      containers:
      - name: kate
        image: andrewwebber/kate
        imagePullPolicy: Always
        securityContext:
          privileged: true
        command:
          - /usr/local/bin/kate
        # Refresh to aggressive, useful for testing
        args: ["-e", "60"]
        volumeMounts:
        - name: docker-config
          mountPath: /root/.docker
        - name: varrun
          mountPath: /var/run
          readOnly: false
        - mountPath: /var/run/docker.socket
          name: docker-socket
          readOnly: false
        - mountPath: /var/lib/docker
          name: docker
          readOnly: true
        - name: sysfs
          mountPath: /sys
          readOnly: true
        - mountPath: /tmp
          name: cve
        ports:
          - name: http
            containerPort: 8080
      - name: clair
        image: quay.io/coreos/clair:v1.2.6
        args:
          - "-config"
          - "/config/config.yaml"
        ports:
        - containerPort: 6060
        - containerPort: 6061
        env:
          - name: TMPDIR
            value: "/tmp"
        volumeMounts:
        - mountPath: /config
          name: secret-volume
        - mountPath: /tmp
          name: cve
